// ─────────────────────────────────────────────────────────────────
//  Gallery — Configuration
//  Add photos to the photos array. Each entry is self-contained.
//  All frame keys are optional — unset keys fall back to defaults.
// ─────────────────────────────────────────────────────────────────

const GALLERY = {

  // ── Identity ─────────────────────────────────────────────────
  title:     'GALLERY',
  handle:    'PTXERO',
  flickrUrl: 'https://www.flickr.com/people/198130461@N06/',

  // ── Roll label ───────────────────────────────────────────────
  rolls: [
    { id: '004', label: 'TwoPiece x PaidInBlood', notes: '', desc: 'Photos taken for Two Piece and Paid In Blood + Others; Pensacola, American Legion Post 33' },
    { id: '001', label: 'Gavin x Missy', notes: '', desc: 'Portraits of my brother and his girlfiend.' },
    { id: '002', label: 'New Orleans', notes: '', desc: 'Film photos taken in New Orleans.' },
    { id: '003', label: 'Nashville', notes: '', desc: 'Film photos taken in Nashville.' },
    { id: '005', label: 'RF', notes: '', desc: '' },
  ],

  // ── Frame defaults ───────────────────────────────────────────
  // Every photo inherits these. Override per photo in frame: {}
  frameDefaults: {
    style:        'dashed',            // 'solid' | 'dashed' | 'dotted'
    width:        1,                   // border px
    color:        '#c8f542',           // border + corner color '#c8f542' lime green,'#42d4f5' cyan,'#f542a8'pink,'#f5a542' orange
    offset:       6,                   // offset shadow px (0 = off)
    offsetColor:  '#1a1a22',           // shadow color
    corners:      true,                // show corner glyphs
    cornerChars:  ['╔','╗','╚','╝'],   // TL TR BL BR
    cornerSize:   10,                  // glyph font size px
    scan:         true,                // hover scanline sweep
    scanColor:    'rgba(200,245,66,0.07)',
  },

  // ── Photos ───────────────────────────────────────────────────
  // frame: {} inherits all defaults. Override any key per photo.
  // You can find the static link by searching: og:image
  // Template:
  // {
  //   roll:       '001',
  //   url:        'https://live.staticflickr.com/...',
  //   flickrPage: 'https://flic.kr/p/...',
  //   shot:       '004',
  //   caption:    'Caption here',
  //   film:       'KODAK GOLD 200',
  //   tags:       ['film', 'street'],
  //   frame: {
  //     style:  'solid',
  //     color:  '#42d4f5',
  //     corners: false,
  //   },
  // },

  photos: [
    //Two Piece & Paid In Blood
   {
     roll:       '004',
     url:        'https://live.staticflickr.com/65535/54845780578_3d1d583ed4_b.jpg',
     flickrPage: 'https://flic.kr/p/2rywXLw',
     shot:       '001',
     caption:    '',
     film:       'Sony A7RIV',
     tags:       ['hardcore', 'concert', 'music'],
     frame: {},
   },
   {
     roll:       '004',
     url:        'https://live.staticflickr.com/65535/54845863890_8e1076edbf_b.jpg',
     flickrPage: 'https://flic.kr/p/2ryxowW',
     shot:       '002',
     caption:    '',
     film:       'Sony A7RIV',
     tags:       ['hardcore', 'concert', 'music'],
     frame: {},
   },
   {
     roll:       '004',
     url:        'https://live.staticflickr.com/65535/54845773034_393a3bfede_b.jpg',
     flickrPage: 'https://flic.kr/p/2rywVws',
     shot:       '003',
     caption:    '',
     film:       'Sony A7RIV',
     tags:       ['hardcore', 'concert', 'music'],
     frame: {},
   },
   {
     roll:       '004',
     url:        'https://live.staticflickr.com/65535/54845780568_a3f6863596_b.jpg',
     flickrPage: 'https://flic.kr/p/2rywXLm',
     shot:       '004',
     caption:    '',
     film:       'Sony A7RIV',
     tags:       ['hardcore', 'concert', 'music'],
     frame: {},
   },
   {
     roll:       '004',
     url:        'https://live.staticflickr.com/65535/54845524266_d340f23677_b.jpg',
     flickrPage: 'https://flic.kr/p/2ryvDzm',
     shot:       '005',
     caption:    '',
     film:       'Sony A7RIV',
     tags:       ['hardcore', 'concert', 'music'],
     frame: {},
   },
   {
     roll:       '004',
     url:        'https://live.staticflickr.com/65535/54845780558_3578886e3a_b.jpg',
     flickrPage: 'https://flic.kr/p/2rywXLb',
     shot:       '006',
     caption:    '',
     film:       'Sony A7RIV',
     tags:       ['hardcore', 'concert', 'music'],
     frame: {},
   },
   {
     roll:       '004',
     url:        'https://live.staticflickr.com/65535/54845524316_5874acd8aa_b.jpg',
     flickrPage: 'https://flic.kr/p/2ryvDAd',
     shot:       '007',
     caption:    '',
     film:       'Sony A7RIV',
     tags:       ['hardcore', 'concert', 'music'],
     frame: {},
   },
   {
     roll:       '004',
     url:        'https://live.staticflickr.com/65535/54845524306_6d249dab2c_b.jpg',
     flickrPage: 'https://flic.kr/p/2ryvDA3',
     shot:       '008',
     caption:    '',
     film:       'Sony A7RIV',
     tags:       ['hardcore', 'concert', 'music'],
     frame: {},
   },
    //Gavin x Missy
    {
      roll:       '001',
      url:        'https://live.staticflickr.com/65535/54634076872_cd74fe2b74_b.jpg',
      flickrPage: 'https://flic.kr/p/2rePUXQ',
      shot:       '001',
      caption:    '',
      film:       'Sony A7RIV',
      tags:       [],
      frame:      {},
    },
    {
      roll:       '001',
      url:        'https://live.staticflickr.com/65535/54634074622_6b9def97b1_b.jpg',
      flickrPage: 'https://flic.kr/p/2rePVCC',
      shot:       '002',
      caption:    '',
      film:       'Sony A7RIV',
      tags:       [],
      frame:      {},
    },
    {
      roll:       '001',
      url:        'https://live.staticflickr.com/65535/54634936566_c73cbd9e2b_b.jpg',
      flickrPage: 'https://flic.kr/p/2reUkbW',
      shot:       '003',
      caption:    '',
      film:       'Sony A7RIV',
      tags:       [],
      frame:      {},
    },
    {
      roll:       '001',
      url:        'https://live.staticflickr.com/65535/54635155314_3918b2711c_b.jpg',
      flickrPage: 'https://flic.kr/p/2reVsds',
      shot:       '004',
      caption:    '',
      film:       'Sony A7RIV',
      tags:       [],
      frame:      {},
    },
    {
      roll:       '001',
      url:        'https://live.staticflickr.com/65535/54178275712_89a65586a8_b.jpg',
      flickrPage: 'https://flic.kr/p/2qxxPPW',
      shot:       '005',
      caption:    '',
      film:       'Sony A7RIV',
      tags:       [],
      frame:      {},
    },
    {
      roll:       '001',
      url:        'https://live.staticflickr.com/65535/54179430733_b347c8dd9c_h.jpg',
      flickrPage: 'https://flic.kr/p/2qxDKb6',
      shot:       '006',
      caption:    '',
      film:       'Sony A7RIV',
      tags:       [],
      frame:      {},
    },
    {
      roll:       '001',
      url:        'https://live.staticflickr.com/65535/54635240700_9f613fa53a_b.jpg',
      flickrPage: 'https://flic.kr/p/2reVTAC',
      shot:       '007',
      caption:    '',
      film:       'Sony A7RIV',
      tags:       [],
      frame:      {},
    },
    
    //New Orleans
    {
     roll:       '002',
     url:        'https://live.staticflickr.com/65535/54486365278_dac7b9da1c_b.jpg',
     flickrPage: 'https://flic.kr/p/2r1LS81',
     shot:       '001',
     caption:    'A drag queen falls onto a chair while performing a lady gaga song',
     film:       'Fuji 400',
     tags:       ['film', 'new orleans', 'drag'],
     frame: {},
   },
   {
     roll:       '002',
     url:        'https://live.staticflickr.com/65535/54485247052_0c3b90ec50_b.jpg',
     flickrPage: 'https://flic.kr/p/2r1F8Hf',
     shot:       '002',
     caption:    'A woman enjoys an alcoholoc drink from within a schoolbus painted like the Mystery Machine from Scooby Doo',
     film:       'Fuji 400',
     tags:       ['film', 'new orleans', 'street', 'mystery machine'],
     frame: {},
   },
   {
     roll:       '002',
     url:        'https://live.staticflickr.com/65535/54485247482_df2706e8ff_b.jpg',
     flickrPage: 'https://flic.kr/p/2r1F8QE',
     shot:       '003',
     caption:    'A man smokes a cigarette beside an orange traffic cone in front of a tall building',
     film:       'Fuji 400',
     tags:       ['film', 'new orleans', 'street'],
     frame: {},
   },
   {
     roll:       '002',
     url:        'https://live.staticflickr.com/65535/54486089336_5a1c939a0f_b.jpg',
     flickrPage: 'https://flic.kr/p/2r1Ks6o',
     shot:       '004',
     caption:    'Two woman with cameras slung across their shoulders carry drinks in the street',
     film:       'Fuji 400',
     tags:       ['film', 'new orleans', 'street'],
     frame: {},
   },
   {
     roll:       '002',
     url:        'https://live.staticflickr.com/65535/54485248482_8d981df956_b.jpg',
     flickrPage: 'https://flic.kr/p/2r1F98U',
     shot:       '005',
     caption:    'A masked person holds a sign that reads "WE WONT EAT CAKE FOR OPUS DEI", he is a part of a protest',
     film:       'Fuji 400',
     tags:       ['film', 'new orleans', 'street', 'protest'],
     frame: {},
   },
   {
     roll:       '002',
     url:        'https://live.staticflickr.com/65535/54485248642_040c15cca3_b.jpg',
     flickrPage: 'https://flic.kr/p/2r1F9bE',
     shot:       '006',
     caption:    'A photo of many protesters, the main subject is a woman holding a cardboard sign reading "FUCK EACH OTHER NOT THE PLANET"',
     film:       'Fuji 400',
     tags:       ['film', 'new orleans', 'street', 'protest'],
     frame: {},
   },
   {
     roll:       '002',
     url:        'https://live.staticflickr.com/65535/54485246722_6b40ea189e_b.jpg',
     flickrPage: 'https://flic.kr/p/2r1F8By',
     shot:       '007',
     caption:    'Me and my friends :)',
     film:       'Fuji 400',
     tags:       ['film', 'new orleans', 'street'],
     frame: {},
   },

   //Nashville
   {
     roll:       '003',
     url:        'https://live.staticflickr.com/65535/54778752089_37dce40237_b.jpg',
     flickrPage: 'https://flic.kr/p/2rsBqwV',
     shot:       '001',
     caption:    'A man holding a cardboard sign reading "SAVING FOR PU$$y EAtiNg LESSONS"',
     film:       'Kodak Ultramax 400',
     tags:       ['film', 'nashville', 'street', 'sign'],
     frame: {},
   },
   {
     roll:       '003',
     url:        'https://live.staticflickr.com/65535/54778860870_bb8862bea2_b.jpg',
     flickrPage: 'https://flic.kr/p/2rsBYSs',
     shot:       '002',
     caption:    'A man holding a cardboard sign reading "EAt more Pussy"',
     film:       'Kodak Ultramax 400',
     tags:       ['film', 'nashville', 'street', 'sign'],
     frame: {},
   },
   {
     roll:       '003',
     url:        'https://live.staticflickr.com/65535/54778763273_ca58d6af15_b.jpg',
     flickrPage: 'https://flic.kr/p/2rsBtRK',
     shot:       '003',
     caption:    'A group of ladies wearing brightly colored wigs outside of Morgan Wallens "This Bar"',
     film:       'Kodak Ultramax 400',
     tags:       ['film', 'nashville', 'street'],
     frame: {},
   },
   {
     roll:       '003',
     url:        'https://live.staticflickr.com/65535/54778863590_a1262d523d_b.jpg',
     flickrPage: 'https://flic.kr/p/2rsBZFm',
     shot:       '004',
     caption:    'A man taking the photo of a woman in a wedding dress while a woman in a white cowboy hat stands beside her',
     film:       'Kodak Ultramax 400',
     tags:       ['film', 'nashville', 'street'],
     frame: {},
   },
   {
     roll:       '003',
     url:        'https://live.staticflickr.com/65535/54778878435_392325f41e_b.jpg',
     flickrPage: 'https://flic.kr/p/2rsC56i',
     shot:       '005',
     caption:    'A couple sitting on the sidewalk eating food',
     film:       'Kodak Ultramax 400',
     tags:       ['film', 'nashville', 'street'],
     frame: {},
   },
   {
     roll:       '003',
     url:        'https://live.staticflickr.com/65535/54777739637_ef1b430350_b.jpg',
     flickrPage: 'https://flic.kr/p/2rsweyR',
     shot:       '006',
     caption:    'A man takes a selfie with a large group of ladies dress as old ladies',
     film:       'Kodak Ultramax 400',
     tags:       ['film', 'nashville', 'street', 'old ladies', 'selfie'],
     frame: {},
   },
   {
     roll:       '003',
     url:        'https://live.staticflickr.com/65535/54778830958_d03e424831_b.jpg',
     flickrPage: 'https://flic.kr/p/2rsBPYJ',
     shot:       '007',
     caption:    'Two Street Photographers sharing a laugh',
     film:       'Kodak Ultramax 400',
     tags:       ['film', 'nashville', 'street', 'camera'],
     frame: {},
   },
   {
     roll:       '003',
     url:        'https://live.staticflickr.com/65535/54778748204_37529b7839_b.jpg',
     flickrPage: 'https://flic.kr/p/2rsBpnW',
     shot:       '008',
     caption:    'A woman stands in the corner trying not to throw up white a man in a bright yellow jumpsuit holds a bouquet of flowers and checks his phone.',
     film:       'Kodak Ultramax 400',
     tags:       ['film', 'nashville', 'street'],
     frame: {},
   },

   //RF
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240628905_c9d25b6695_b.jpg',
     flickrPage: 'https://flic.kr/p/2saqEqi',
     shot:       '001',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240464119_9efc4f755b_b.jpg',
     flickrPage: 'https://flic.kr/p/2sapPra',
     shot:       '002',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55239323642_0e274e7d9c_b.jpg',
     flickrPage: 'https://flic.kr/p/2saiYpL',
     shot:       '003',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240370583_8fbf01c435_b.jpg',
     flickrPage: 'https://flic.kr/p/2sapkCt',
     shot:       '004',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240369883_8e93452d0a_b.jpg',
     flickrPage: 'https://flic.kr/p/2sapkqp',
     shot:       '005',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240632095_b911c04f26_b.jpg',
     flickrPage: 'https://flic.kr/p/2saqFni',
     shot:       '006',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240225436_9edf2a1b2c_b.jpg',
     flickrPage: 'https://flic.kr/p/2saoAtW',
     shot:       '007',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55239322892_3acc6dcf5e_b.jpg',
     flickrPage: 'https://flic.kr/p/2saiYbQ',
     shot:       '008',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240366543_0cc8d95262_b.jpg',
     flickrPage: 'https://flic.kr/p/2sapjqP',
     shot:       '009',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55239323207_b43652d33c_b.jpg',
     flickrPage: 'https://flic.kr/p/2saiYhg',
     shot:       '010',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240629435_cee1fe15b5_b.jpg',
     flickrPage: 'https://flic.kr/p/2saqEzr',
     shot:       '011',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55260156187_f128542698_b.jpg',
     flickrPage: 'https://flic.kr/p/2sc9Kcz',
     shot:       '012',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240229256_db97eac65c_b.jpg',
     flickrPage: 'https://flic.kr/p/2saoBBN',
     shot:       '013',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
   {
     roll:       '005',
     url:        'https://live.staticflickr.com/65535/55240225381_6e43099b6b_b.jpg',
     flickrPage: 'https://flic.kr/p/2saoAsZ',
     shot:       '014',
     caption:    '',
     film:       '',
     tags:       [],
     frame: {},
   },
  ],

};
