const fs = require('fs'), vm = require('vm');
const src = fs.readFileSync(require('path').join(__dirname, '..', 'worker', 'searchnet-worker.js'), 'utf8').replace('export default {', 'const __handler = {');
const mod = { exports: {} };
const W = (() => { const ctx = { module: mod, exports: mod.exports, console, URL, URLSearchParams, TextEncoder, TextDecoder, Response: class { constructor(b, o) { this.body = b; this.status = (o || {}).status || 200; this.headers = new Map(Object.entries(((o || {}).headers) || {})); } }, setTimeout, Request: class {}, get fetch() { return globalThis.fetch; } }; vm.createContext(ctx); vm.runInContext(src, ctx); return mod.exports; })();
const ok = (c, m) => console.log((c ? '✓ ' : '✗ ') + m);
const RSS = (items) => `<?xml version="1.0"?><rss><channel>${items.map((i) => `<item><title>${i.t}</title><link>${i.l}</link><pubDate>Tue, 07 Oct 2026 10:00:00 GMT</pubDate><description>${i.d || ''}</description>${i.s ? `<source url="https://x.example">${i.s}</source>` : ''}</item>`).join('')}</channel></rss>`;
const calls = [];
globalThis.fetch = async (u, o) => { calls.push(String(u)); const url = String(u);
  const R = (body, ct = 'application/json') => ({ ok: true, status: 200, url, headers: { get: (k) => k.toLowerCase() === 'content-type' ? ct : null }, json: async () => JSON.parse(body), text: async () => body });
  if (url.includes('desuarchive.org')) return R(JSON.stringify({ 0: { posts: [{ num: '77', thread_num: '70', board: { shortname: 'g' }, timestamp: 1700000000, name: 'Anonymous', title: 'hurricane thread', comment: 'isaias &gt; hype', media: null }] } }));
  if (url.includes('a.4cdn.org/pol/catalog.json')) return R(JSON.stringify([{ threads: [{ no: 5, sub: 'Hurricane Isaias', com: 'incoming', name: 'Anonymous', time: 1700000001, replies: 3, tim: 1, ext: '.jpg' }, { no: 6, sub: 'unrelated', com: 'x', name: 'A', time: 1 }] }]));
  if (url.includes('a.4cdn.org/')) return R('[]');
  if (url.includes('wikipedia.org/w/api.php')) return R(JSON.stringify({ query: { search: [{ pageid: 9, title: 'Hurricane Isaias', snippet: 'a <span>storm</span>', timestamp: '2026-01-01T00:00:00Z', wordcount: 500 }] } }));
  if (url.includes('reddit.com/search.json')) return { ok: false, status: 403, headers: { get: () => '' }, text: async () => '', json: async () => ({}) };
  if (url.includes('pullpush.io')) return R(JSON.stringify({ data: [{ id: 'abc', title: 'Isaias megathread', subreddit: 'florida', author: 'u1', created_utc: 1700000000, url: 'https://www.reddit.com/r/florida/comments/abc/x/', permalink: '/r/florida/comments/abc/x/', score: 10, num_comments: 2, is_video: false, selftext: 'text' }] }));
  if (url.includes('youtube.com/results')) return R('<html><script>var ytInitialData = {"contents":{"a":[{"videoRenderer":{"videoId":"abc123","title":{"runs":[{"text":"Isaias landfall"}]},"ownerText":{"runs":[{"text":"WX Channel"}]},"lengthText":{"simpleText":"3:21"},"viewCountText":{"simpleText":"12K views"}}}]}};</script></html>', 'text/html');
  if (url.includes('/api/v1/search') && !url.includes('algolia')) return { ok: false, status: 530, headers: { get: () => '' }, text: async () => '', json: async () => ({}) };
  if (url.includes('news.google.com')) return R(RSS([{ t: 'Isaias nears Florida coast', l: 'https://www.tampabay.com/isaias', s: 'Tampa Bay Times' }]), 'text/xml');
  if (url.includes('bing.com')) return R(RSS([{ t: 'John Smith obituary', l: 'https://www.legacy.com/us/obituaries/x/john-smith', d: 'passed away' }]), 'text/xml');
  if (url.includes('gdeltproject')) return R(JSON.stringify({ articles: [{ url: 'https://news.example/a', title: 'Storm update', seendate: '20260807T120000Z', domain: 'news.example', language: 'English' }] }));
  if (url.includes('hn.algolia')) return R(JSON.stringify({ hits: [{ objectID: '1', title: 'Hurricane tracking', url: 'https://hn.example', author: 'pg', created_at_i: 1, points: 5, num_comments: 2 }] }));
  if (url.includes('archive.org')) return R(JSON.stringify({ response: { docs: [{ identifier: 'isaias1', title: 'Isaias 2020', description: ['d'], date: '2020-08-01T00:00:00Z', mediatype: 'texts' }] } }));
  const RESULTS = '<html><title>Results</title><body>news ' + '<a href=x>r</a>'.repeat(8) + '</body></html>';
  if (url === 'https://blog.example/') return R('<html><head><link rel="alternate" type="application/rss+xml" title="Blog feed" href="/feed.xml"></head><body><form action="/search"><input type="text" name="q"></form></body></html>', 'text/html');
  if (url.startsWith('https://blog.example/search?q=')) return R(RESULTS, 'text/html');
  if (url === 'https://nofeed.example/') return R('<html><body>hi</body></html>', 'text/html');
  if (url === 'https://nofeed.example/feed') return R('<?xml version="1.0"?><rss></rss>', 'application/rss+xml');
  if (url === 'https://wp.example/') return R('<html><head><link rel="stylesheet" href="/wp-content/themes/x.css"></head><body></body></html>', 'text/html');
  if (url.startsWith('https://wp.example/?s=')) return R(RESULTS, 'text/html');
  return { ok: false, status: 404, headers: { get: () => '' }, text: async () => '', json: async () => ({}) };
};
(async () => {
  const S = W.SOURCES;
  let r = await S.news({ q: 'hurricane isaias', qx: 'Florida' }, 10);
  ok(r.length === 1 && r[0].platform === 'news' && r[0].author === 'Tampa Bay Times' && r[0].id.startsWith('news:') && r[0].media === 'post', 'news: Google News item branded, source name kept');
  ok(calls.some((c) => c.includes('q=hurricane%20isaias%20Florida')), 'news: extra terms appended to the query');
  r = await S.web({ q: 'john smith', qx: 'obituary' }, 10); ok(r.length === 1 && r[0].platform === 'web' && r[0].author === 'legacy.com', 'web: Bing RSS item, author = host');
  r = await S.gdelt({ q: 'storm' }, 10); ok(r.length === 1 && r[0].platform === 'news' && r[0].posted_at === Math.floor(Date.parse('2026-08-07T12:00:00Z') / 1000), 'gdelt: date parsed');
  r = await S.hn({ q: 'x' }, 5); ok(r.length === 1 && r[0].id === 'hn:1' && r[0].likes === 5, 'hn: story mapped');
  r = await S.archive({ q: 'x' }, 5); ok(r.length === 1 && r[0].id === 'archive:isaias1' && r[0].hashtags === '', 'archive: doc mapped');
  // media=video from a video topic must not drop articles
  r = await S.news({ q: 'x', media: 'video' }, 10); ok(r.length === 1, 'news: articles kept even when the topic wants video');
  const d = await W.discoverSite('https://blog.example/post/1'); ok(d.feeds.length === 1 && d.feeds[0].url === 'https://blog.example/feed.xml' && d.search === 'https://blog.example/search?q={q}', 'discover: feed link + search form found');
  const d4 = await W.discoverSite('https://wp.example/'); ok(d4.platform === 'wordpress' && d4.search === 'https://wp.example/?s={q}', 'discover: WordPress fingerprint → /?s= verified');
  ok(d.candidates[0].verified === true, 'discover: the form candidate was verified with a real query');
  r = await S.fourchan({ q: 'hurricane isaias', boards: 'pol' }, 10); ok(r.length === 2 && r[0].id === '4chan:g:77' && r[1].id === '4chan:pol:5' && r[1].media === 'image' && r[1].text.includes('Hurricane Isaias'), '4chan: archive hit + live catalog match (unrelated thread skipped)');
  r = await S.wikipedia({ q: 'hurricane isaias' }, 5); ok(r.length === 1 && r[0].id === 'wikipedia:en:9' && /Hurricane_Isaias/.test(r[0].url), 'wikipedia: article mapped');
  r = await S.reddit({ q: 'isaias', media: 'everything' }, 5); ok(r.length === 1 && /reddit:/.test(r[0].id), 'reddit: falls back to PullPush when reddit.com says 403');
  r = await S.youtube({ q: 'isaias' }, 5); ok(r.length === 1 && r[0].id === 'youtube:abc123' && r[0].duration === 201 && r[0].views === 12000 && r[0].author === 'WX Channel', 'youtube: falls back to the results page when Invidious is down');
  const d2 = await W.discoverSite('https://nofeed.example/'); ok(d2.feeds.length === 1 && d2.feeds[0].url === 'https://nofeed.example/feed' && d2.search_guess, 'discover: falls back to /feed probe and a search guess');
})();
