const pw = (await import(process.env.PW_MODULE || 'playwright')).default; const ROOT = new URL('../../..', import.meta.url).pathname;
import { spawn } from 'node:child_process';
const srv = spawn('python3', ['-m', 'http.server', '8770', '--bind', '127.0.0.1'], { cwd: ROOT, stdio: 'ignore' }); await new Promise((r) => setTimeout(r, 800));
let bad = 0; const ok = (c, m) => { if (!c) bad++; console.log((c ? '✓ ' : '✗ ') + m); };
const browser = await pw.chromium.launch(); const ctx = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
const NOW = Math.floor(Date.now() / 1000);
const post = (id, author, text, ts, kw = {}) => Object.assign({ id: 'mastodon:' + id, platform: 'mastodon', post_id: String(id), media: 'post', url: 'https://m.example/@' + author + '/' + id, author, author_name: author, text, hashtags: 'isaias', posted_at: ts, likes: 2, reposts: 0, replies: 0, views: 0 }, kw);
const items = [];
for (let d = 20; d > 2; d--) if (d % 3 === 0) items.push(post('q' + d, 'calm' + (d % 4), 'Isaias update: forecasters watching the track #isaias', NOW - d * 86400));
const angry = ['Duke Energy still has no power for 200k people. Unacceptable. Resign. #isaias', 'Gas gouging at $9 a gallon after Isaias. Disgusting. Boycott them. #isaias', 'Three days, NO POWER, NO ANSWERS!!! Outrage in Collier County #isaias', 'Duke Energy outage map is a lie. Shameful. Lawsuit when? #isaias'];
for (let i = 0; i < 16; i++) items.push(post('b' + i, 'mad' + (i % 7), angry[i % 4], NOW - (i % 2) * 86400 - 600 * i, { likes: 20, replies: 18, reposts: 3 }));
for (let i = 0; i < 4; i++) items.push(post('c' + i, 'copy' + i, 'Sign the petition: restore power in Collier County now https://petition.example/isaias #isaias', NOW - 3600 * i, { likes: 1 }));
items.push(post('first', 'wxguy', 'Duke Energy says outages could last a week after Isaias #isaias', NOW - 86400 - 7200, { likes: 900, reposts: 400, replies: 30 }));
items.push(post('s1', 'nhc', 'Isaias is moving ENE at 8 mph with maximum sustained winds of 45 mph. #isaias', NOW - 7000));
items.push(post('s2', 'nhc2', 'Isaias now moving at 10 mph, winds of 110 mph. #isaias', NOW - 3500));
for (let i = 0; i < 4; i++) items.push(post('old' + i, 'mem' + i, 'Remembering Hurricane Isaias in 2020, the record season ' + i + ' #isaias', NOW - 100 - i));
items.push(post('n1', 'wxguy2', 'Duke Energy said 200,000 customers are without power in Collier County after Isaias. #isaias', NOW - 3 * 86400, { likes: 50 }));
items.push(post('n2', 'u9', 'Duke Energy said 200,000 customers lost power in Collier County, the utility confirmed. #isaias', NOW - 2 * 86400, { platform: 'news', author: 'naplesnews.com', author_name: 'Naples Daily News', id: 'news:n2', url: 'https://www.naplesnews.com/n2' }));
items.push(post('n3', 'u10', 'Down to 12,000 customers without power as of this morning after Isaias #isaias', NOW - 86400));
items.push(post('n4', 'u11', 'The county commission hearing on Isaias gouging is on October 14. Show up. #isaias', NOW - 3600));
items.push(post('n5', 'u12', 'Hearing on Isaias price gouging October 14 at the county commission, bring receipts. #isaias', NOW - 3000));
await ctx.route(/share\.ptxero\.net/, async (route) => {
  const req = route.request(); const u = new URL(req.url());
  const json = (o, s = 200) => route.fulfill({ status: s, contentType: 'application/json', headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': '*', 'Access-Control-Allow-Methods': '*' }, body: JSON.stringify(o) });
  if (req.method() === 'OPTIONS') return json({});
  if (u.pathname === '/health') return json({ ok: true, worker: 'searchnet', version: '1.8', hub: '2.0' });
  if (u.pathname === '/me') return json({ uid: 'X', owner: false, today: { fetch: 0, writes: 0 }, limits: { fetch: 400, writes: 300 }, store: { bytes: 0, blobs: 0, by_app: {} } });
  if (u.pathname === '/id') return json({ ok: true });
  if (u.pathname === '/search') return json({ items: u.searchParams.get('source') === 'mastodon' ? items : [] });
  return json({ error: 'unmocked ' + u.pathname }, 404);
});
await ctx.route(/wikipedia|wikimedia|datamuse|googleapis|gstatic/, (r) => r.abort());
const p = await ctx.newPage(); const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://127.0.0.1:8770/searchnet/index.html?mode=browser#sources', { waitUntil: 'domcontentloaded' }); await p.waitForTimeout(1500);
const api = (path, opts) => p.evaluate(([path, opts]) => window.SearchNetLocal.request(path, opts), [path, opts]);
if (!(await api('/api/sources')).sources.some((x) => x.source === 'mastodon')) await api('/api/sources', { method: 'POST', body: { preset: 'mastodon', param: 'mastodon.social' } });
const t = await api('/api/topics', { method: 'POST', body: { name: 'Hurricane Isaias', seeds: ['isaias'], settings: { breadth: 1, media: 'everything', window: 'all' }, run: false } });
const j = await api('/api/topics/' + t.id + '/run', { method: 'POST' });
for (let i = 0; i < 80; i++) { const st = await p.evaluate((id) => (window.SearchNetLocal.jobs[id] || {}).state, j.id); if (st === 'done' || st === 'error') break; await p.waitForTimeout(300); }
const T = await api('/api/topics/' + t.id);
ok(T.settings.signal && T.settings.signal.state === 'surging' && ['hot', 'uproar'].includes(T.settings.signal.heat), 'run: badge stored on the topic (' + JSON.stringify(T.settings.signal) + ')');
const s = await api('/api/topics/' + t.id + '/signals');
ok(s.trend.state === 'surging' && s.heat.level === 'uproar' && s.drivers[0].author === 'wxguy' && s.coordination.copies[0].accounts === 4, 'signals route: surging · uproar · wxguy drove it · 4 copies');
ok(s.issues.map((i) => i.category).includes('infrastructure / outages'), 'signals route: reads as infrastructure / outages');
await p.evaluate((h) => { location.hash = h; }, '#topics'); await p.waitForTimeout(800);
const card = await p.textContent('.tcard');
ok(/surging/.test(card) && /uproar|hot/.test(card), 'topic card shows the badges (' + card.replace(/\s+/g, ' ').slice(0, 90) + ')');
await p.evaluate((h) => { location.hash = h; }, '#topic/' + t.id); await p.waitForTimeout(3000);
const body = await p.textContent('#tBody');
ok(/In short/.test(body) && /Since when/.test(body) && /What started it/.test(body) && /Momentum/.test(body) && /picking up/.test(body) && /Collier County/.test(body), 'dossier: IN SHORT card with what / since / origin / momentum / where');
ok(/the burst followed @wxguy/.test(body), 'dossier: origin names the kickoff post');
ok(/Next/.test(body) && /@wxguy|source|dossier|storylines/.test(body), 'dossier: next steps listed');
ok(/Claims/.test(body) && /an outlet confirms/.test(body) && /Naples Daily News/.test(body), 'dossier: claims card with an outlet-confirmed claim');
ok(/Numbers that move/.test(body) && /customers/.test(body) && /200k → 12k/.test(body), 'dossier: numbers that move (customers 200k → 12k)');
ok(/Coming up/.test(body) && /October 14/.test(body) && /coming up: October 14/.test(body), 'dossier: dates ahead, also in IN SHORT next');
ok(/(thin|fair|solid) read/.test(body), 'dossier: trust label on IN SHORT');
ok(/winds mph/.test(body) && /moving mph/.test(body), 'dossier: winds and forward speed are two series');
ok(/posts are about the 2020 one with the same name/.test(body) && /KEEP 2020 OUT/.test(body), 'dossier: the 2020 storm with the same name is flagged');
ok(/National Hurricane Center/.test(body), 'dossier: weather topics carry the safety line');
ok(/✕ not this/.test(body), 'dossier: storylines have a not-this button');
await p.click('[data-anti="2020"]'); await p.waitForTimeout(2500);
const T2 = await api('/api/topics/' + t.id); ok((T2.settings.anti || []).includes('2020'), 'KEEP 2020 OUT adds the year as an anti-keyword');

ok(/What.*confirms/.test(body.replace(/\s+/g, ' ')), 'dossier: What line uses the confirmed claim');
ok(/Signals/.test(body) && /surging/.test(body), 'dossier: SIGNALS card with the headline');
ok(/Trend/.test(body) && /Heat/.test(body) && /Spread/.test(body) && /Who moved it/.test(body) && /What kind of problem/.test(body) && /Same words, same links/.test(body), 'dossier: trend · heat · spread · drivers · problem · coordination cards');
ok(/Just before the burst/.test(body) && /duke energy/.test(body), 'dossier: lead-lag names Duke Energy before the burst');
ok(await p.evaluate(() => document.querySelectorAll('#tBody .heat i').length === 1 && document.querySelectorAll('#tBody .dcard a.pill[href^="http"]').length > 10), 'dossier: heat bar and post links present');
await p.screenshot({ path: '/tmp/signals.png', fullPage: false });
ok(errs.length === 0, 'no page errors' + (errs.length ? ' → ' + errs.slice(0, 3).join(' | ') : ''));
await browser.close(); srv.kill(); process.exit(bad ? 1 : 0);
